version: "3"

tasks:

  set_weights:
    cmds:
      - docker compose --env-file .vali.env -f docker-compose.yml run --entrypoint "python src/cycle/calculate_and_schedule_weights.py" control_node
  control_node_dev:
    cmds:
      - ENV_FILE=.vali.env python -m validator.control_node.src.main
  
  query_node_dev:
    cmds: 
      - ENV_FILE=.vali.env python -m validator.query_node.src.main

  entry_node_dev:
    cmds:
      - uvicorn validator.entry_node.src.server:app --reload --host 0.0.0.0 --port 8091 --env-file .vali.env

  dev_setup:
    cmds:
      - >
        docker compose --env-file .vali.env -f docker-compose.yml -f docker-compose.utils.yml up -d --build
        $(docker compose config --services | grep -vE 'query_node|control_node|entry_node')
      # Now use control_node_dev etc

  miners_dev:
    cmds:
      - |
        ENV=DEV uvicorn miner.server:app --reload --host 0.0.0.0 --port 4001 --env-file .1.env --log-level debug
        ENV=DEV uvicorn miner.server:app --reload --host 0.0.0.0 --port 4002 --env-file .2.env --log-level debug
        wait
  
  createm:
    cmds:
      - bash start_miners.sh