version: "3"

tasks:

  set_weights:
    cmds:
      - docker compose --env-file .prod.env -f docker-compose.prod.yml run --entrypoint "python src/cycle/calculate_and_schedule_weights.py" control_node
  control_node_dev:
    cmds:
      - ENV_FILE=.dev.env python -m validator.control_node.src.main
  
  query_node_dev:
    cmds: 
      - ENV_FILE=.dev.env python -m validator.query_node.src.main

  entry_node_dev:
    cmds:
      - uvicorn validator.entry_node.src.server:app --reload --host 0.0.0.0 --port 8091 --env-file .dev.env

  dev_setup:
    cmds:
      - docker compose --env-file .dev.env -f docker-compose.prod.yml up -d
      - docker compose --env-file .dev.env -f docker-compose.prod.yml -f docker-compose.utils.yml up -d
      - docker kill query_node control_node

  miners_dev:
    cmds:
      - |
        uvicorn miner.server:app --reload --host 0.0.0.0 --port 4001 --env-file .1.env --log-level debug &
        uvicorn miner.server:app --reload --host 0.0.0.0 --port 4002 --env-file .2.env --log-level debug &
        wait
  
  createm:
    cmds:
      - |
        for env_file in .*.env; do
          if grep -q "NODE_PORT" "$env_file"; then
            node_port=$(grep "NODE_PORT" "$env_file" | cut -d '=' -f2)
            service_name="miner_$(echo $env_file | sed 's/\.//g' | sed 's/env//')"
            pm2 start $service_name 'uvicorn miner.server:app --reload --host 0.0.0.0 --port $node_port --env-file $env_file --log-level debug & '
          fi
        done